//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentoring.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mentoring.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Role has been added to user {0}.
        /// </summary>
        internal static string AddedCareer {
            get {
                return ResourceManager.GetString("AddedCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career have accepted user {0} as a Mentee.
        /// </summary>
        internal static string MenteeActive {
            get {
                return ResourceManager.GetString("MenteeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} have completed the Mentee Form and is waiting for Career Approval.
        /// </summary>
        internal static string MenteePendingApproval {
            get {
                return ResourceManager.GetString("MenteePendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career have rejected user {0} as a Mentee.
        /// </summary>
        internal static string MenteeRejected {
            get {
                return ResourceManager.GetString("MenteeRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career have accepted user {0} as a Mentor.
        /// </summary>
        internal static string MentorActive {
            get {
                return ResourceManager.GetString("MentorActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} have completed the Mentor Form and is waiting for Career Approval.
        /// </summary>
        internal static string MentorPendingApproval {
            get {
                return ResourceManager.GetString("MentorPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career have rejected user {0} as a Mentor.
        /// </summary>
        internal static string MentorRejected {
            get {
                return ResourceManager.GetString("MentorRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Role has been removed from user {0}.
        /// </summary>
        internal static string RemovedCareer {
            get {
                return ResourceManager.GetString("RemovedCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} have been created.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
    }
}
